org: sebastianchu
service: api-web-scraping

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::971808350791:role/LabRole
  environment:
    DYNAMODB_TABLE: SismosTable

functions:
  scrape_table:
    handler: handler.lambda_handler
    package:
      include:
        - ./**
    events:
      - http:
          path: /scrape/table
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    SismosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SismosTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

